spring.application.name=gdrive

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:mem:gdrive
spring.datasource.username=sa
spring.datasource.username=

server.error.include-stacktrace=never
server.error.include-exception=false

jwt.secret=REMOVED_JWT_SECRET=
crypt.secret=REMOVED_CRYPT_SECRET=
